.github/workflows/release-please.yml
=> Run prepack before publish

src/stores/JsonViewerStore.ts
Fixes: https://github.com/TexteaInc/json-viewer/issues/11#issuecomment-1254059739
=> fix: missing `props.defaultInspectDepth`

package.json, src/components/DataTypes/Object.tsx, tests/index.test.tsx, yarn.lock
Refs: https://github.com/meyfa/group-items/pull/80
=> refactor: use `group-items`

src/stores/typeRegistry.tsx
=> style: add padding to `null` and `undefined`

package.json, src/components/DataKeyPair.tsx, src/index.tsx, tests/index.test.tsx, yarn.lock
=> fix: ignore rootName when its false

src/components/DataKeyPair.tsx, src/stores/JsonViewerStore.ts, src/type.ts
I think the most popular case of usage is just showing json to inspect it
=> Set editable to false by default

docs/pages/full/index.tsx, src/components/DataKeyPair.tsx
Fixes: https://github.com/TexteaInc/json-viewer/issues/92
=> fix: editable for basic value

src/stores/JsonViewerStore.ts, src/type.ts
Fixes: https://github.com/TexteaInc/json-viewer/issues/90
=> feat: support `props.collapseStringsAfterLength` with false

src/stores/typeRegistry.tsx
Fixes: https://github.com/TexteaInc/json-viewer/issues/94
=> fix: set `overflowWrap` to `anywhere`

docs/pages/full/index.tsx
=> chore: opt form view

.editorconfig, src/components/DataTypes/createEasyType.tsx, src/stores/typeRegistry.tsx, tests/index.test.tsx
Now dots show only when a string is expanded. It's incorrect behaviour.
Also adjusted `.editorconfig`
=> Invert logic for showing dots

.github/workflows/release-please.yml, package.json
close #135 
related: https://github.com/yarnpkg/yarn/issues/8580
=> fix: remove `workspaces` in `package.json` before release

src/components/DataTypes/Function.tsx, src/components/DataTypes/Object.tsx, src/stores/typeRegistry.tsx, tests/index.test.tsx
=> feat(ui): replace triple dots (...) with ellipsis (…)

src/components/DataKeyPair.tsx, src/components/mui/DataBox.tsx
https://github.com/TexteaInc/json-viewer/pull/169#issuecomment-1383191190
this bad boy caused the doc bundling error in #168 
Why? IDK 😢
=> refactor: use `sx` rather than `styled`

docs/package.json, yarn.lock
See https://github.com/shuding/nextra/issues/1210#issuecomment-1386219113
=> chore(docs): bump version to fix dev error

src/components/DataKeyPair.tsx, src/components/DataTypes/createEasyType.tsx, src/index.tsx, src/stores/typeRegistry.tsx
=> refactor: fix eslint warning and the style of code

docs/pages/index.mdx
=> docs: add description for `Props`

src/components/DataKeyPair.tsx
=> fix: editing value not correct

rollup.config.ts
=> build: disable `externalHelpers`

package.json, rollup.config.ts, yarn.lock
This should bring down the size from 103.33KB to 78.48KB which is the size that we normally shipped.
=> fix: use swc in the right way

src/browser.tsx
closes #453 
Hmm.. there is no clear document on the usage of CDN version. We should add one in the doc.
=> feat: expose dataTypes, themes and utils in browser build

.github/dependabot.yml
Referer: https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot
=> chore: add pattern to dependabot

src/index.tsx, src/utils/index.ts, tests/util.test.tsx
=> feat: add utils `getPathValue`
