TexteaInc/json-viewer

- examples/basic/pages/index.tsx
- src/components/DataKeyPair.tsx
- src/components/DataTypes/Array.tsx
- src/components/DataTypes/Object.tsx
- src/index.tsx
- src/stores/JsonViewerStore.ts
- src/stores/typeRegistry.tsx
- src/type.ts
- src/utils/index.ts
Fixes: https://github.com/TexteaInc/json-viewer/issues/19
> feat: support `groupArraysAfterLength`

- src/components/DataKeyPair.tsx
- src/hooks/useCopyToClipboard.ts
The PR improves the UX by adding a copy success responds to user input.
The PR does 3 things:
- Introduce a new hook `useClipboard` that will return a `copy` function, a `reset` function, and a `copied` boolean.
- Prefer `navigator.clipboard` API, and then failover to the `copy-to-clipboard` package.
- Introduce `useClipboard` to the `DataKeyPair` component.
> feat: show copy success

- examples/basic/pages/index.tsx
- src/components/DataKeyPair.tsx
- src/components/DataTypes/Object.tsx
- src/hooks/useInspect.ts
- src/stores/JsonViewerStore.ts
- src/stores/typeRegistry.tsx
- src/type.ts
Fixes: https://github.com/TexteaInc/json-viewer/issues/19
> fix: state on nested array

- src/components/DataTypes/Object.tsx
- src/index.tsx
- src/stores/JsonViewerStore.ts
- src/stores/typeRegistry.tsx
- src/type.ts
> feat: support `props.maxDisplayLength`

- examples/basic/pages/index.tsx
- src/components/DataTypes/createEasyType.tsx
- src/stores/typeRegistry.tsx
Trying to add support for the `bigint` type.
> feat: support `bigint` type

- src/components/DataKeyPair.tsx
- src/components/DataTypes/Object.tsx
- src/stores/JsonViewerStore.ts
- src/type.ts
- tests/index.test.tsx
I read a real-world product and find we miss some fields
https://github.com/rowyio/rowy/blob/a3f8db47f641999a00f8b7c97bbb38d44726e131/src/components/fields/Json/SideDrawerField.tsx#L96-L111
> feat: backport support for `props.quotesOnKeys` and `props.sortKeys`

- README.md
- examples/basic/pages/index.tsx
- package.json
- src/index.tsx
- src/type.ts
- src/utils/index.ts
- tests/index.test.tsx
- tests/util.test.tsx
- yarn.lock
> feat: add helper function `createDataType`

- examples/basic/pages/index.tsx
- src/components/DataKeyPair.tsx
- src/components/DataTypes/createEasyType.tsx
- src/index.tsx
- src/stores/JsonViewerStore.ts
- src/type.ts
- tests/index.test.tsx
Fixes: https://github.com/TexteaInc/json-viewer/issues/59
> feat: backport support for `props.displayDataTypes`

- src/index.tsx
- src/stores/typeRegistry.tsx
- tests/index.test.tsx
Fixes: https://github.com/TexteaInc/json-viewer/issues/62
> fix: move type registry into component state

- src/index.tsx
- src/stores/typeRegistry.tsx
Fixes: https://github.com/TexteaInc/json-viewer/issues/66
> fix: type registry runs multiple times

- src/components/DataKeyPair.tsx
- src/components/DataTypes/Object.tsx
- src/stores/typeRegistry.tsx
- src/utils/index.ts
There is no need to use `else` if in previous `if` was `return` instruction. It enhances reading at least.
> Simplify ifs

- README.md
- src/components/DataKeyPair.tsx
- src/components/DataTypes/Object.tsx
- src/hooks/useInspect.ts
- src/stores/typeRegistry.tsx
- src/type.ts
- src/utils/index.ts
- tests/index.test.tsx
> Some enhancements

- package.json
> fix: browser field cause vite build fail

- docs/pages/full/index.tsx
- src/components/DataTypes/Object.tsx
- src/index.tsx
- src/stores/JsonViewerStore.ts
- src/type.ts
- tests/index.test.tsx
Issue: https://github.com/TexteaInc/json-viewer/issues/101
There is a tiny problem in two places:
https://github.com/Yazawazi/json-viewer/blob/main/src/components/DataTypes/Object.tsx#L53-L66
https://github.com/Yazawazi/json-viewer/blob/main/src/components/DataTypes/Object.tsx#L95-L110
The `pl` (`padding-left`) property causes the gap to be increased on the left side. My description may not be clear, so here are the pictures:
`displayObjectSize`: `true`
`displayObjectSize`: `false`
> feat: support `displayObjectSize`

- src/components/DataKeyPair.tsx
- src/stores/typeRegistry.tsx
- src/type.ts
- src/utils/index.ts
Fixes: https://github.com/TexteaInc/json-viewer/issues/106
> feat: support path in dataType

- src/components/DataKeyPair.tsx
- src/hooks/useCopyToClipboard.ts
- src/index.tsx
- src/stores/JsonViewerStore.ts
- src/type.ts
- yarn.lock
Fixes: https://github.com/TexteaInc/json-viewer/issues/109
> feat: support `props.onCopy`

- src/stores/typeRegistry.tsx
When a string is collapsed, it always shows the three dots (...) at the end in both states, collapsed and uncollapsed.
This PR should fix this behaviour.
(Unfortunately I'm unable to test this locally. I'm unable get this project up and running. I can build the sources with 'yarn && yarn build', but when I add it to another project (even a fresh create-react-app) I got errors 'Invalid hook call. Hooks can only be called inside of the body of a function component.' and 'Uncaught TypeError: Cannot read properties of null (reading 'useMemo')'. I'm sorry, my skills end here.)
> Show three dots only on collapsed strings

- package.json
This fixes https://github.com/TexteaInc/json-viewer/issues/133.
I think that it's because the dev-kit lib got put as a dev dependency, so when you npm install, it doesn't come along.
I think it's just an oopsie. Moving it from devDependencies to dependencies in package.json will fix this.
I think that a better fix will be to not even have this "DevelopmentError" in the code as it seems rather odd, but this at least fixes the issue.
> fix: cannot resolve `@textea/dev-kit/utils`

- package.json
- yarn.lock
Console output after yarn install:
```console
➤ YN0002: │ @textea/json-viewer@workspace:. doesn't provide vite (pba117), requested by @vitejs/plugin-react
➤ YN0002: │ @textea/json-viewer@workspace:. [897a1] doesn't provide vite (pb4639), requested by @vitejs/plugin-react
```
`@vitejs/plugin-react` dev dependency has `vite` as peer dependency.
All transitive dependency should be installed respectively.
> fix: add `vite` as dev dependency

- src/components/DataKeyPair.tsx
> fix(ui): remove left margin in key-value separator

- .eslintrc.js
- docs/components/JsonViewerPreview.tsx
- docs/pages/_app.tsx
- docs/pages/full/index.tsx
- src/browser.tsx
- src/components/DataKeyPair.tsx
- src/components/DataTypeLabel.tsx
- src/components/DataTypes/Function.tsx
- src/components/Icons.tsx
- src/components/mui/DataBox.tsx
- src/hooks/useInspect.ts
- src/index.tsx
- src/stores/typeRegistry.tsx
- tsconfig.json
https://github.com/TexteaInc/json-viewer/pull/169#issuecomment-1383064405
> style: force import type usage and add jsx-runtime rules

- docs/theme.config.js
See [nextra-theme-blog@2.0.2](https://github.com/shuding/nextra/releases/tag/nextra-theme-blog%402.0.2)
> docs: remove deprecated `titleSuffix`

- docs/pages/index.mdx
This PR fix the broken link in home page of `types.ts` file.
> docs: fix type file broken link in home page

- package.json
There is an incorrect reference in the `package.json` as the `src` folder is not published to npm, which gives an error when using it inside a project with `type: module`
`Could not find a declaration file for module '@textea/json-viewer'. 'D:/DEV/DEVOPS/gerald/node_modules/@textea/json-viewer/dist/index.mjs' implicitly has an 'any' type.`
> fix: correct types reference for module projects

- src/components/DataKeyPair.tsx
- src/components/DataTypeLabel.tsx
- src/components/DataTypes/Object.tsx
closes #93 
The text was selectable in V1 but not in V2.
This is because we didn't noticed that `userselect: none` was introduced by MUI accidentally.
Add back `userselect: text` CSS.
And we also improved the selectable range to only the content, which is different from [`react-json-view`](https://github.com/mac-s-g/react-json-view). (Check the [#screenshots](#screenshots))
> fix: key and value text should be selectable

- .eslintrc.js
- .gitignore
- package.json
- rollup.config.ts
- src/index.tsx
- yarn.lock
related: #140 #168
This PR introduced [@swc/plugin-transform-imports](https://github.com/swc-project/plugins/blob/main/packages/transform-imports/README.md) to [minimize](https://mui.com/material-ui/guides/minimizing-bundle-size/) the bundle size of MUI.
It will transform the import statement into path import to reduce the amount of modules being pulled in.
```js
import { Box, SvgIcon } from '@mui/material'
->
import Box from '@mui/material/Box'
import SvgIcon from '@mui/material/SvgIcon'
> fix: reduce MUI size by using `@swc/plugin-transform-imports`

- package.json
- rollup.config.ts
- src/index.tsx
- src/stores/JsonViewerStore.ts
- src/stores/typeRegistry.tsx
- yarn.lock
closes #144 
This PR migrates the usage of `zustand` v4 to remove the deprecation message
```
[DEPRECATED] zustand/context will be removed in the future version. Please use `import { createStore, useStore } from "zustand"` for context usage. See: https://github.com/pmndrs/zustand/discussions/1180
[DEPRECATED] default export is deprecated, instead import { create } from'zustand'
```
> fix: migrate `zustand` to remove the deprecation message

- src/hooks/useCopyToClipboard.ts
- src/utils/index.ts
- tests/util.test.tsx
Circular Reference -> `[Circular]`, close #225 
BigInt -> `"123456789123"`
Map -> `Object` if all of key are `string` or `number`
Set -> `Array`
> fix: improve copying on circular reference / BigInt / Map / Set

- docs/tsconfig.json
- package.json
- src/components/DataTypes/Object.tsx
- src/stores/JsonViewerStore.ts
- src/stores/typeRegistry.tsx
- src/utils/index.ts
- tsconfig.json
- yarn.lock
1. Enable `strict` type checking
2. Iterate through Map with `.forEach`
3. Iterate through `Iterable` with iterator API.
> refactor: eliminate type warning and improve type checking

- docs/pages/full/index.tsx
- src/components/DataKeyPair.tsx
- src/components/DataTypes/Object.tsx
- src/index.tsx
- src/stores/JsonViewerStore.ts
- src/type.ts
Add a highlighting effect to the key of the changed data.
> Shortcoming: Because the value is only compared within the `<DataKeyPair />` component, highlighting only display at the deepest key where changed. Adding and removing properties do not cause highlighting.
* enableHighlight: Whether to highlight the changed
Feel free to make your requests and suggestions.
close #267
> feat: highlight changed

- README.md
- docs/pages/index.mdx
- package.json
- rollup.config.ts
- tsconfig.json
- yarn.lock
https://emotion.sh/docs/for-library-authors
> If you do choose to use Emotion in your library, it is best to list the Emotion packages as peer dependencies in your package.json. This ensures that your library and the consuming application get the same instance of each Emotion package.
@pionxzh @rtritto
> fix(dep)!: move `emotion` and `mui` to peerDependencies

- README.md
- docs/pages/full/index.tsx
- src/components/DataKeyPair.tsx
- src/components/DataTypes/Boolean.tsx
- src/components/DataTypes/Date.tsx
- src/components/DataTypes/Function.tsx
- src/components/DataTypes/Null.tsx
- src/components/DataTypes/Number.tsx
- src/components/DataTypes/Object.tsx
- src/components/DataTypes/String.tsx
- src/components/DataTypes/Undefined.tsx
- src/components/DataTypes/createEasyType.tsx
- src/components/DataTypes/index.ts
- src/index.tsx
- src/stores/typeRegistry.tsx
- src/type.ts
- src/utils/index.ts
- tests/index.test.tsx
1. Expose built-in types like string, number, function...etc. This allows users to customize the behavior of existing components, or use part of them to combine a new data type. closes #136 \
\
For example, you can add a `PostComponent` after a link.\
2. \*\***BREAKING CHANGES**\*\* Add `serialize` and `deserialize` options for editing. You will need to provide `serialize`, `deserialize` and `Editor` to enable to editing feature. closes #284 
3. Base on breaking changes from 2, we will provide a new API `defineDataType` for declaring the datatype. And the original `createDataType` will be dropped.
> feat: expose built-in types

- .github/workflows/release-please.yml
- src/hooks/useThemeDetector.ts
CI started to fail on releasing... Let's try to upgrade the release action to V2.
> ci: use `JS-DevTools/npm-publish@v2`

- package.json
- yarn.lock
ref: https://github.com/import-js/eslint-plugin-import/pull/2447
> chore: replace `eslint-plugin-import` with `eslint-plugin-i`

- src/components/DataTypes/String.tsx
Currently, super long string cannot be partially selected without collapsing due to "setShowRest" triggering on click
> fix: super long string can be partially selected without collapsing

- docs/pages/how-to/data-types.mdx
- src/components/DataKeyPair.tsx
- src/components/DataTypes/defineEasyType.tsx
- src/type.ts
> feat: improve built-in editor with autoFocus and better keyboard control

- src/components/DataKeyPair.tsx
- src/components/DataTypes/Object.tsx
- src/type.ts
- tests/index.test.tsx
> fix: should handle key and path of nested grouped array with nestedIndex

- package.json
- fix https://github.com/magic-akari/seamless-scroll-polyfill/issues/147
#442
> fix: remove `browser` from package.json

- src/components/DataTypes/Object.tsx
- src/index.tsx
> fix: improve part of ui not covered by theme color

- docs/pages/how-to/built-in-types.mdx
- src/components/DataKeyPair.tsx
This PR fixes the issue when the key was either missing (when `rootName=false`) or the key was rendered as `"root"` if it wasn't set.
For example, for the given object:-
```
const value: any = {
text: 'Hello World'
}
value.self = value;
```
Before (with  `rootName=false`)
After (with  `rootName=false`)
Before (with default `rootName`)
After (with default `rootName`)
> fix: missing/incorrect key when rendering self referential objects

- src/components/DataTypes/Object.tsx
Update Object datatype for correct pluralization of Items
> Update Object datatype for correct pluralization of Items

- docs/pages/how-to/built-in-types.mdx
The example source code for defineEasyType was referencing toggleType from the previous example. Changed it to use correct example.
> Fix: Update built-in-types.mdx to reference correct type
